module.exports.stateList = [

    {
        state: "Andhra Pradesh",
        stateCode: "AP",
        districts: [
            { serialNumber: "01", districtName: "Anakapalli", districtCode: "ANP" },
            { serialNumber: "02", districtName: "Anantapur", districtCode: "ATP" },
            { serialNumber: "03", districtName: "Bapatla", districtCode: "BPT" },
            { serialNumber: "04", districtName: "Chittoor", districtCode: "CTR" },
            { serialNumber: "05", districtName: "East Godavari", districtCode: "EGD" },
            { serialNumber: "06", districtName: "Eluru", districtCode: "ELR" },
            { serialNumber: "07", districtName: "Guntur", districtCode: "GNT" },
            { serialNumber: "08", districtName: "Krishna", districtCode: "KRI" },
            { serialNumber: "09", districtName: "Kakinada", districtCode: "KKD" },
            { serialNumber: "10", districtName: "Konaseema", districtCode: "KSM" },
            { serialNumber: "11", districtName: "Kurnool", districtCode: "KUR" },
            { serialNumber: "12", districtName: "Nandyal", districtCode: "NDL" },
            { serialNumber: "13", districtName: "Nellore", districtCode: "NEL" },
            { serialNumber: "14", districtName: "NTR District", districtCode: "NTR" },
            { serialNumber: "15", districtName: "Palnadu", districtCode: "PLN" },
            { serialNumber: "16", districtName: "Parvathipuram Manyam", districtCode: "PVM" },
            { serialNumber: "17", districtName: "Prakasam", districtCode: "PRA" },
            { serialNumber: "18", districtName: "Srikakulam", districtCode: "SRK" },
            { serialNumber: "19", districtName: "Sri Potti Sriramulu Nellore", districtCode: "SPS" },
            { serialNumber: "20", districtName: "Tirupati", districtCode: "TPT" },
            { serialNumber: "21", districtName: "Visakhapatnam", districtCode: "VSK" },
            { serialNumber: "22", districtName: "Vizianagaram", districtCode: "VZM" },
            { serialNumber: "23", districtName: "West Godavari", districtCode: "WGD" },
            { serialNumber: "24", districtName: "YSR Kadapa", districtCode: "YSR" },
            { serialNumber: "25", districtName: "Alluri Sitharama Raju", districtCode: "ASR" },
            { serialNumber: "26", districtName: "Sri Satya Sai", districtCode: "SSS" }
        ],
        totalDistrictCount: 26
    },

    
    
    {
        state: "Arunachal Pradesh",
        stateCode: "AR",
        districts: [
            { serialNumber: "01", districtName: "Tawang", districtCode: "TWN" },
            { serialNumber: "02", districtName: "West Kameng", districtCode: "WKM" },
            { serialNumber: "03", districtName: "East Kameng", districtCode: "EKM" },
            { serialNumber: "04", districtName: "Pakke Kessang", districtCode: "PKK" },
            { serialNumber: "05", districtName: "Papum Pare", districtCode: "PPR" },
            { serialNumber: "06", districtName: "Kurung Kumey", districtCode: "KKM" },
            { serialNumber: "07", districtName: "Kra Daadi", districtCode: "KDD" },
            { serialNumber: "08", districtName: "Lower Subansiri", districtCode: "LSZ" },
            { serialNumber: "09", districtName: "Upper Subansiri", districtCode: "USZ" },
            { serialNumber: "10", districtName: "West Siang", districtCode: "WSG" },
            { serialNumber: "11", districtName: "Siang", districtCode: "SGN" },
            { serialNumber: "12", districtName: "Upper Siang", districtCode: "USG" },
            { serialNumber: "13", districtName: "Lower Siang", districtCode: "LSG" },
            { serialNumber: "14", districtName: "Leparada", districtCode: "LPR" },
            { serialNumber: "15", districtName: "East Siang", districtCode: "ESG" },
            { serialNumber: "16", districtName: "Dibang Valley", districtCode: "DBV" },
            { serialNumber: "17", districtName: "Lower Dibang Valley", districtCode: "LDV" },
            { serialNumber: "18", districtName: "Anjaw", districtCode: "ANJ" },
            { serialNumber: "19", districtName: "Lohit", districtCode: "LHT" },
            { serialNumber: "20", districtName: "Namsai", districtCode: "NAM" },
            { serialNumber: "21", districtName: "Changlang", districtCode: "CHG" },
            { serialNumber: "22", districtName: "Tirap", districtCode: "TRP" },
            { serialNumber: "23", districtName: "Longding", districtCode: "LNG" },
            { serialNumber: "24", districtName: "Shi Yomi", districtCode: "SYM" },
            { serialNumber: "25", districtName: "Lepa Rada", districtCode: "LPR" },
            { serialNumber: "26", districtName: "Kamle", districtCode: "KML" }
        ],
        totalDistrictCount: 26
    },
    
    {
        state: "Assam",
        stateCode: "AS",
        districts: [
            { serialNumber: "01", districtName: "Baksa", districtCode: "BKS" },
            { serialNumber: "02", districtName: "Barpeta", districtCode: "BPT" },
            { serialNumber: "03", districtName: "Biswanath", districtCode: "BIS" },
            { serialNumber: "04", districtName: "Bongaigaon", districtCode: "BNG" },
            { serialNumber: "05", districtName: "Cachar", districtCode: "CAC" },
            { serialNumber: "06", districtName: "Charaideo", districtCode: "CHD" },
            { serialNumber: "07", districtName: "Chirang", districtCode: "CHR" },
            { serialNumber: "08", districtName: "Darrang", districtCode: "DAR" },
            { serialNumber: "09", districtName: "Dhemaji", districtCode: "DHE" },
            { serialNumber: "10", districtName: "Dhubri", districtCode: "DHB" },
            { serialNumber: "11", districtName: "Dibrugarh", districtCode: "DBR" },
            { serialNumber: "12", districtName: "Dima Hasao", districtCode: "DMA" },
            { serialNumber: "13", districtName: "Goalpara", districtCode: "GLP" },
            { serialNumber: "14", districtName: "Golaghat", districtCode: "GLG" },
            { serialNumber: "15", districtName: "Hailakandi", districtCode: "HLD" },
            { serialNumber: "16", districtName: "Hojai", districtCode: "HOJ" },
            { serialNumber: "17", districtName: "Jorhat", districtCode: "JOR" },
            { serialNumber: "18", districtName: "Kamrup", districtCode: "KMP" },
            { serialNumber: "19", districtName: "Kamrup Metropolitan", districtCode: "KMPT" },
            { serialNumber: "20", districtName: "Karbi Anglong", districtCode: "KRA" },
            { serialNumber: "21", districtName: "Karimganj", districtCode: "KRG" },
            { serialNumber: "22", districtName: "Kokrajhar", districtCode: "KKR" },
            { serialNumber: "23", districtName: "Lakhimpur", districtCode: "LKH" },
            { serialNumber: "24", districtName: "Majuli", districtCode: "MJL" },
            { serialNumber: "25", districtName: "Morigaon", districtCode: "MRG" },
            { serialNumber: "26", districtName: "Nagaon", districtCode: "NGO" },
            { serialNumber: "27", districtName: "Nalbari", districtCode: "NLB" },
            { serialNumber: "28", districtName: "Sivasagar", districtCode: "SVG" },
            { serialNumber: "29", districtName: "Sonitpur", districtCode: "SNP" },
            { serialNumber: "30", districtName: "South Salmara-Mankachar", districtCode: "SSM" },
            { serialNumber: "31", districtName: "Tinsukia", districtCode: "TSK" },
            { serialNumber: "32", districtName: "Udalguri", districtCode: "UDG" },
            { serialNumber: "33", districtName: "West Karbi Anglong", districtCode: "WKA" },
            { serialNumber: "34", districtName: "Bajali", districtCode: "BAJ" },
            { serialNumber: "35", districtName: "Tamulpur", districtCode: "TML" }
        ],
        totalDistrictCount: 35
    },
    {
        state: "Bihar",
        stateCode: "BR",
        districts: [
            { serialNumber: "01", districtName: "Araria", districtCode: "ARA" },
            { serialNumber: "02", districtName: "Arwal", districtCode: "ARW" },
            { serialNumber: "03", districtName: "Aurangabad", districtCode: "AUR" },
            { serialNumber: "04", districtName: "Banka", districtCode: "BNK" },
            { serialNumber: "05", districtName: "Begusarai", districtCode: "BGS" },
            { serialNumber: "06", districtName: "Bhagalpur", districtCode: "BGP" },
            { serialNumber: "07", districtName: "Bhojpur", districtCode: "BHP" },
            { serialNumber: "08", districtName: "Buxar", districtCode: "BXR" },
            { serialNumber: "09", districtName: "Darbhanga", districtCode: "DBG" },
            { serialNumber: "10", districtName: "East Champaran", districtCode: "ECP" },
            { serialNumber: "11", districtName: "Gaya", districtCode: "GAY" },
            { serialNumber: "12", districtName: "Gopalganj", districtCode: "GPL" },
            { serialNumber: "13", districtName: "Jamui", districtCode: "JMU" },
            { serialNumber: "14", districtName: "Jehanabad", districtCode: "JHD" },
            { serialNumber: "15", districtName: "Kaimur", districtCode: "KMR" },
            { serialNumber: "16", districtName: "Katihar", districtCode: "KTR" },
            { serialNumber: "17", districtName: "Khagaria", districtCode: "KGR" },
            { serialNumber: "18", districtName: "Kishanganj", districtCode: "KSG" },
            { serialNumber: "19", districtName: "Lakhisarai", districtCode: "LKS" },
            { serialNumber: "20", districtName: "Madhepura", districtCode: "MDP" },
            { serialNumber: "21", districtName: "Madhubani", districtCode: "MDB" },
            { serialNumber: "22", districtName: "Munger", districtCode: "MGR" },
            { serialNumber: "23", districtName: "Muzaffarpur", districtCode: "MZR" },
            { serialNumber: "24", districtName: "Nalanda", districtCode: "NLD" },
            { serialNumber: "25", districtName: "Nawada", districtCode: "NWD" },
            { serialNumber: "26", districtName: "Patna", districtCode: "PTN" },
            { serialNumber: "27", districtName: "Purnia", districtCode: "PRN" },
            { serialNumber: "28", districtName: "Rohtas", districtCode: "RHT" },
            { serialNumber: "29", districtName: "Saharsa", districtCode: "SHR" },
            { serialNumber: "30", districtName: "Samastipur", districtCode: "SMP" },
            { serialNumber: "31", districtName: "Saran", districtCode: "SRN" },
            { serialNumber: "32", districtName: "Sheikhpura", districtCode: "SKP" },
            { serialNumber: "33", districtName: "Sheohar", districtCode: "SHR" },
            { serialNumber: "34", districtName: "Sitamarhi", districtCode: "STM" },
            { serialNumber: "35", districtName: "Siwan", districtCode: "SWN" },
            { serialNumber: "36", districtName: "Supaul", districtCode: "SPL" },
            { serialNumber: "37", districtName: "Vaishali", districtCode: "VSH" },
            { serialNumber: "38", districtName: "West Champaran", districtCode: "WCP" }
        ],
        totalDistrictCount: 38
    },
    
    {
        state: "Chhattisgarh",
        stateCode: "CG",
        districts: [
            { serialNumber: "01", districtName: "Balod", districtCode: "BLD" },
            { serialNumber: "02", districtName: "Baloda Bazar", districtCode: "BLB" },
            { serialNumber: "03", districtName: "Balrampur", districtCode: "BLR" },
            { serialNumber: "04", districtName: "Bastar", districtCode: "BTR" },
            { serialNumber: "05", districtName: "Bemetara", districtCode: "BMT" },
            { serialNumber: "06", districtName: "Bijapur", districtCode: "BJP" },
            { serialNumber: "07", districtName: "Bilaspur", districtCode: "BSP" },
            { serialNumber: "08", districtName: "Dantewada", districtCode: "DTW" },
            { serialNumber: "09", districtName: "Dhamtari", districtCode: "DMT" },
            { serialNumber: "10", districtName: "Durg", districtCode: "DRG" },
            { serialNumber: "11", districtName: "Gariaband", districtCode: "GRB" },
            { serialNumber: "12", districtName: "Gaurela-Pendra-Marwahi", districtCode: "GPM" },
            { serialNumber: "13", districtName: "Janjgir-Champa", districtCode: "JGC" },
            { serialNumber: "14", districtName: "Jashpur", districtCode: "JSP" },
            { serialNumber: "15", districtName: "Kabirdham", districtCode: "KBD" },
            { serialNumber: "16", districtName: "Kanker", districtCode: "KNR" },
            { serialNumber: "17", districtName: "Kondagaon", districtCode: "KDG" },
            { serialNumber: "18", districtName: "Korba", districtCode: "KRB" },
            { serialNumber: "19", districtName: "Koriya", districtCode: "KRY" },
            { serialNumber: "20", districtName: "Mahasamund", districtCode: "MSM" },
            { serialNumber: "21", districtName: "Mungeli", districtCode: "MNG" },
            { serialNumber: "22", districtName: "Narayanpur", districtCode: "NRP" },
            { serialNumber: "23", districtName: "Raigarh", districtCode: "RGH" },
            { serialNumber: "24", districtName: "Raipur", districtCode: "RPR" },
            { serialNumber: "25", districtName: "Rajnandgaon", districtCode: "RNJ" },
            { serialNumber: "26", districtName: "Sukma", districtCode: "SKM" },
            { serialNumber: "27", districtName: "Surajpur", districtCode: "SRJ" },
            { serialNumber: "28", districtName: "Surguja", districtCode: "SRG" },
            { serialNumber: "29", districtName: "Balrampur-Ramanujganj", districtCode: "BLR" },
            { serialNumber: "30", districtName: "Manendragarh-Chirmiri-Bharatpur", districtCode: "MCB" },
            { serialNumber: "31", districtName: "Sarangarh-Bilaigarh", districtCode: "SRB" },
            { serialNumber: "32", districtName: "Khairagarh-Chhuikhadan-Gandai", districtCode: "KCG" },
            { serialNumber: "33", districtName: "Mohla-Manpur-Chowki", districtCode: "MMC" }
        ],
        totalDistrictCount: 33
    },
    
    {
        state: "Goa",
        stateCode: "GA",
        districts: [
            { serialNumber: "01", districtName: "North Goa", districtCode: "NGO" },
            { serialNumber: "02", districtName: "South Goa", districtCode: "SGO" }
        ],
        totalDistrictCount: 2
    },
    {
        state: "Gujarat",
        stateCode: "GJ",
        districts: [
            { serialNumber: "01", districtName: "Ahmedabad", districtCode: "AMD" },
            { serialNumber: "02", districtName: "Amreli", districtCode: "AMR" },
            { serialNumber: "03", districtName: "Anand", districtCode: "AND" },
            { serialNumber: "04", districtName: "Aravalli", districtCode: "ARV" },
            { serialNumber: "05", districtName: "Banaskantha", districtCode: "BKT" },
            { serialNumber: "06", districtName: "Bharuch", districtCode: "BHC" },
            { serialNumber: "07", districtName: "Bhavnagar", districtCode: "BHG" },
            { serialNumber: "08", districtName: "Botad", districtCode: "BOT" },
            { serialNumber: "09", districtName: "Chhota Udaipur", districtCode: "CHD" },
            { serialNumber: "10", districtName: "Dahod", districtCode: "DHD" },
            { serialNumber: "11", districtName: "Dang", districtCode: "DAN" },
            { serialNumber: "12", districtName: "Devbhoomi Dwarka", districtCode: "DBD" },
            { serialNumber: "13", districtName: "Gandhinagar", districtCode: "GDN" },
            { serialNumber: "14", districtName: "Gir Somnath", districtCode: "GNS" },
            { serialNumber: "15", districtName: "Jamnagar", districtCode: "JAM" },
            { serialNumber: "16", districtName: "Junagadh", districtCode: "JUN" },
            { serialNumber: "17", districtName: "Kutch", districtCode: "KUC" },
            { serialNumber: "18", districtName: "Kheda", districtCode: "KHD" },
            { serialNumber: "19", districtName: "Mahisagar", districtCode: "MHS" },
            { serialNumber: "20", districtName: "Mehsana", districtCode: "MEH" },
            { serialNumber: "21", districtName: "Narmada", districtCode: "NAR" },
            { serialNumber: "22", districtName: "Navsari", districtCode: "NAV" },
            { serialNumber: "23", districtName: "Panchmahal", districtCode: "PAM" },
            { serialNumber: "24", districtName: "Patan", districtCode: "PAT" },
            { serialNumber: "25", districtName: "Porbandar", districtCode: "POR" },
            { serialNumber: "26", districtName: "Rajkot", districtCode: "RAJ" },
            { serialNumber: "27", districtName: "Sabarkantha", districtCode: "SAB" },
            { serialNumber: "28", districtName: "Surat", districtCode: "SUR" },
            { serialNumber: "29", districtName: "Surendranagar", districtCode: "SNG" },
            { serialNumber: "30", districtName: "Tapi", districtCode: "TAP" },
            { serialNumber: "31", districtName: "The Dangs", districtCode: "DAN" },
            { serialNumber: "32", districtName: "Vadodara", districtCode: "VAD" },
            { serialNumber: "33", districtName: "Valsad", districtCode: "VAL" }
        ],
        totalDistrictCount: 33
    },
    {
        state: "Haryana",
        stateCode: "HR",
        districts: [
            { serialNumber: "01", districtName: "Ambala", districtCode: "AMB" },
            { serialNumber: "02", districtName: "Bhiwani", districtCode: "BHI" },
            { serialNumber: "03", districtName: "Charkhi Dadri", districtCode: "CHD" },
            { serialNumber: "04", districtName: "Faridabad", districtCode: "FBD" },
            { serialNumber: "05", districtName: "Fatehabad", districtCode: "FBD" },
            { serialNumber: "06", districtName: "Gurugram", districtCode: "GGM" },
            { serialNumber: "07", districtName: "Hisar", districtCode: "HSR" },
            { serialNumber: "08", districtName: "Jind", districtCode: "JND" },
            { serialNumber: "09", districtName: "Jhajjar", districtCode: "JHJ" },
            { serialNumber: "10", districtName: "Jammu", districtCode: "JAM" },
            { serialNumber: "11", districtName: "Kaithal", districtCode: "KTL" },
            { serialNumber: "12", districtName: "Karnal", districtCode: "KRL" },
            { serialNumber: "13", districtName: "Kurukshetra", districtCode: "KUR" },
            { serialNumber: "14", districtName: "Mahendragarh", districtCode: "MGH" },
            { serialNumber: "15", districtName: "Mewat", districtCode: "MEW" },
            { serialNumber: "16", districtName: "Panchkula", districtCode: "PCL" },
            { serialNumber: "17", districtName: "Panipat", districtCode: "PAN" },
            { serialNumber: "18", districtName: "Rewari", districtCode: "REW" },
            { serialNumber: "19", districtName: "Rohtak", districtCode: "ROH" },
            { serialNumber: "20", districtName: "Sirsa", districtCode: "SIR" },
            { serialNumber: "21", districtName: "Sonipat", districtCode: "SON" },
            { serialNumber: "22", districtName: "Yamunanagar", districtCode: "YAM" }
        ],
        totalDistrictCount: 22
    },
    {
        state: "Himachal Pradesh",
        stateCode: "HP",
        districts: [
            { serialNumber: "01", districtName: "Bilaspur", districtCode: "BIL" },
            { serialNumber: "02", districtName: "Chamba", districtCode: "CHA" },
            { serialNumber: "03", districtName: "Hamirpur", districtCode: "HAM" },
            { serialNumber: "04", districtName: "Kangra", districtCode: "KAN" },
            { serialNumber: "05", districtName: "Kinnaur", districtCode: "KIN" },
            { serialNumber: "06", districtName: "Kullu", districtCode: "KUL" },
            { serialNumber: "07", districtName: "Lahaul and Spiti", districtCode: "LAH" },
            { serialNumber: "08", districtName: "Mandi", districtCode: "MAN" },
            { serialNumber: "09", districtName: "Shimla", districtCode: "SHI" },
            { serialNumber: "10", districtName: "Sirmaur", districtCode: "SIR" },
            { serialNumber: "11", districtName: "Solan", districtCode: "SOL" },
            { serialNumber: "12", districtName: "Una", districtCode: "UNA" }
        ],
        totalDistrictCount: 12
    },
    {
        state: "Jharkhand",
        stateCode: "JH",
        districts: [
            { serialNumber: "01", districtName: "Bokaro", districtCode: "BKO" },
            { serialNumber: "02", districtName: "Chatra", districtCode: "CHA" },
            { serialNumber: "03", districtName: "Deoghar", districtCode: "DEO" },
            { serialNumber: "04", districtName: "Dhanbad", districtCode: "DHA" },
            { serialNumber: "05", districtName: "Dumka", districtCode: "DUM" },
            { serialNumber: "06", districtName: "East Singhbhum", districtCode: "ESB" },
            { serialNumber: "07", districtName: "Garhwa", districtCode: "GAR" },
            { serialNumber: "08", districtName: "Giridih", districtCode: "GIR" },
            { serialNumber: "09", districtName: "Godda", districtCode: "GOD" },
            { serialNumber: "10", districtName: "Gumla", districtCode: "GUM" },
            { serialNumber: "11", districtName: "Hazaribagh", districtCode: "HAZ" },
            { serialNumber: "12", districtName: "Jamtara", districtCode: "JAM" },
            { serialNumber: "13", districtName: "Khunti", districtCode: "KHU" },
            { serialNumber: "14", districtName: "Koderma", districtCode: "KOD" },
            { serialNumber: "15", districtName: "Latehar", districtCode: "LAT" },
            { serialNumber: "16", districtName: "Lohardaga", districtCode: "LOH" },
            { serialNumber: "17", districtName: "Pakur", districtCode: "PAK" },
            { serialNumber: "18", districtName: "Palamu", districtCode: "PAL" },
            { serialNumber: "19", districtName: "Ramgarh", districtCode: "RAM" },
            { serialNumber: "20", districtName: "Ranchi", districtCode: "RAN" },
            { serialNumber: "21", districtName: "Sahibganj", districtCode: "SAH" },
            { serialNumber: "22", districtName: "Seraikela-Kharsawan", districtCode: "SKH" },
            { serialNumber: "23", districtName: "West Singhbhum", districtCode: "WSB" },
            { serialNumber: "24", districtName: "Jamshedpur", districtCode: "JAM" }
        ],
        totalDistrictCount: 24
    },
    {
        state: "Karnataka",
        stateCode: "KA",
        districts: [
            { serialNumber: "01", districtName: "Bagalkote", districtCode: "BAG" },
            { serialNumber: "02", districtName: "Bangalore Rural", districtCode: "BRU" },
            { serialNumber: "03", districtName: "Bangalore Urban", districtCode: "BUR" },
            { serialNumber: "04", districtName: "Belagavi", districtCode: "BEL" },
            { serialNumber: "05", districtName: "Bellary", districtCode: "BEL" },
            { serialNumber: "06", districtName: "Bidar", districtCode: "BID" },
            { serialNumber: "07", districtName: "Chamarajanagar", districtCode: "CHA" },
            { serialNumber: "08", districtName: "Chickballapur", districtCode: "CHB" },
            { serialNumber: "09", districtName: "Chickmagalur", districtCode: "CHM" },
            { serialNumber: "10", districtName: "Chitradurga", districtCode: "CHD" },
            { serialNumber: "11", districtName: "Dakshina Kannada", districtCode: "DAK" },
            { serialNumber: "12", districtName: "Davanagere", districtCode: "DAV" },
            { serialNumber: "13", districtName: "Dharwad", districtCode: "DHA" },
            { serialNumber: "14", districtName: "Gadag", districtCode: "GAD" },
            { serialNumber: "15", districtName: "Gulbarga", districtCode: "GUL" },
            { serialNumber: "16", districtName: "Hassan", districtCode: "HAS" },
            { serialNumber: "17", districtName: "Haveri", districtCode: "HAV" },
            { serialNumber: "18", districtName: "Kodagu", districtCode: "KOD" },
            { serialNumber: "19", districtName: "Kolar", districtCode: "KOL" },
            { serialNumber: "20", districtName: "Koppal", districtCode: "KOP" },
            { serialNumber: "21", districtName: "Mandya", districtCode: "MAN" },
            { serialNumber: "22", districtName: "Mysuru", districtCode: "MYS" },
            { serialNumber: "23", districtName: "Raichur", districtCode: "RAI" },
            { serialNumber: "24", districtName: "Ramanagara", districtCode: "RAM" },
            { serialNumber: "25", districtName: "Shivamogga", districtCode: "SHI" },
            { serialNumber: "26", districtName: "Tumkur", districtCode: "TUM" },
            { serialNumber: "27", districtName: "Udupi", districtCode: "UDU" },
            { serialNumber: "28", districtName: "Uttara Kannada", districtCode: "UTT" },
            { serialNumber: "29", districtName: "Vijayapura", districtCode: "VIJ" },
            { serialNumber: "30", districtName: "Vijayanagara", districtCode: "VIJ" },
            { serialNumber: "31", districtName: "Yadgir", districtCode: "YAD" }
        ],
        totalDistrictCount: 31
    },
    {
        state: "Kerala",
        stateCode: "KL",
        districts: [
            { serialNumber: "01", districtName: "Alappuzha", districtCode: "ALP" },
            { serialNumber: "02", districtName: "Ernakulam", districtCode: "ERN" },
            { serialNumber: "03", districtName: "Idukki", districtCode: "IDK" },
            { serialNumber: "04", districtName: "Kannur", districtCode: "KAN" },
            { serialNumber: "05", districtName: "Kasaragod", districtCode: "KAS" },
            { serialNumber: "06", districtName: "Kollam", districtCode: "KOL" },
            { serialNumber: "07", districtName: "Kottayam", districtCode: "KOT" },
            { serialNumber: "08", districtName: "Kozhikode", districtCode: "KOZ" },
            { serialNumber: "09", districtName: "Malappuram", districtCode: "MAL" },
            { serialNumber: "10", districtName: "Palakkad", districtCode: "PAL" },
            { serialNumber: "11", districtName: "Pathanamthitta", districtCode: "PAT" },
            { serialNumber: "12", districtName: "Thiruvananthapuram", districtCode: "THI" },
            { serialNumber: "13", districtName: "Thrissur", districtCode: "THR" },
            { serialNumber: "14", districtName: "Wayanad", districtCode: "WAY" }
        ],
        totalDistrictCount: 14
    },
    {
        state: "Madhya Pradesh",
        stateCode: "MP",
        districts: [
            { serialNumber: "01", districtName: "Ashoknagar", districtCode: "ASH" },
            { serialNumber: "02", districtName: "Balaghat", districtCode: "BAL" },
            { serialNumber: "03", districtName: "Barwani", districtCode: "BAR" },
            { serialNumber: "04", districtName: "Betul", districtCode: "BET" },
            { serialNumber: "05", districtName: "Bhind", districtCode: "BHI" },
            { serialNumber: "06", districtName: "Bhopal", districtCode: "BHO" },
            { serialNumber: "07", districtName: "Burhanpur", districtCode: "BUR" },
            { serialNumber: "08", districtName: "Chhindwara", districtCode: "CHI" },
            { serialNumber: "09", districtName: "Datti", districtCode: "DAT" },
            { serialNumber: "10", districtName: "Dewas", districtCode: "DEW" },
            { serialNumber: "11", districtName: "Dhar", districtCode: "DHA" },
            { serialNumber: "12", districtName: "Dindori", districtCode: "DIN" },
            { serialNumber: "13", districtName: "Guna", districtCode: "GUN" },
            { serialNumber: "14", districtName: "Gwalior", districtCode: "GWA" },
            { serialNumber: "15", districtName: "Harda", districtCode: "HAR" },
            { serialNumber: "16", districtName: "Hoshangabad", districtCode: "HOS" },
            { serialNumber: "17", districtName: "Indore", districtCode: "IND" },
            { serialNumber: "18", districtName: "Jabalpur", districtCode: "JAB" },
            { serialNumber: "19", districtName: "Jhabua", districtCode: "JHA" },
            { serialNumber: "20", districtName: "Katni", districtCode: "KAT" },
            { serialNumber: "21", districtName: "Khandwa", districtCode: "KHA" },
            { serialNumber: "22", districtName: "Khargone", districtCode: "KHG" },
            { serialNumber: "23", districtName: "Mandla", districtCode: "MAN" },
            { serialNumber: "24", districtName: "Mandsaur", districtCode: "MAN" },
            { serialNumber: "25", districtName: "Morena", districtCode: "MOR" },
            { serialNumber: "26", districtName: "Narsinghpur", districtCode: "NAR" },
            { serialNumber: "27", districtName: "Neemuch", districtCode: "NEE" },
            { serialNumber: "28", districtName: "Pachmarhi", districtCode: "PAC" },
            { serialNumber: "29", districtName: "Panna", districtCode: "PAN" },
            { serialNumber: "30", districtName: "Raisen", districtCode: "RAI" },
            { serialNumber: "31", districtName: "Rajgarh", districtCode: "RAJ" },
            { serialNumber: "32", districtName: "Ratlam", districtCode: "RAT" },
            { serialNumber: "33", districtName: "Rewa", districtCode: "REW" },
            { serialNumber: "34", districtName: "Sagar", districtCode: "SAG" },
            { serialNumber: "35", districtName: "Satna", districtCode: "SAT" },
            { serialNumber: "36", districtName: "Sehore", districtCode: "SEH" },
            { serialNumber: "37", districtName: "Sewda", districtCode: "SEW" },
            { serialNumber: "38", districtName: "Shahdol", districtCode: "SHA" },
            { serialNumber: "39", districtName: "Shajapur", districtCode: "SHA" },
            { serialNumber: "40", districtName: "Sheopur", districtCode: "SHE" },
            { serialNumber: "41", districtName: "Shivpuri", districtCode: "SHI" },
            { serialNumber: "42", districtName: "Sidhi", districtCode: "SID" },
            { serialNumber: "43", districtName: "Singrauli", districtCode: "SIN" },
            { serialNumber: "44", districtName: "Tikamgarh", districtCode: "TIK" },
            { serialNumber: "45", districtName: "Ujjain", districtCode: "UJJ" },
            { serialNumber: "46", districtName: "Umaria", districtCode: "UMA" },
            { serialNumber: "47", districtName: "Vidisha", districtCode: "VID" },
            { serialNumber: "48", districtName: "Anuppur", districtCode: "ANU" },
            { serialNumber: "49", districtName: "Balaghat", districtCode: "BAL" },
            { serialNumber: "50", districtName: "Bhopal", districtCode: "BHO" },
            { serialNumber: "51", districtName: "Madhya", districtCode: "MAD" },
            { serialNumber: "52", districtName: "Satna", districtCode: "SAT" },
            { serialNumber: "53", districtName: "Singrauli", districtCode: "SIN" },
            { serialNumber: "54", districtName: "Guna", districtCode: "GUN" },
            { serialNumber: "55", districtName: "Shivpuri", districtCode: "SHI" }
        ],
        totalDistrictCount: 55
    },
    {
        state: "Maharashtra",
        stateCode: "MH",
        districts: [
            { serialNumber: "01", districtName: "Ahmednagar", districtCode: "AHM" },
            { serialNumber: "02", districtName: "Akola", districtCode: "AKO" },
            { serialNumber: "03", districtName: "Amravati", districtCode: "AMR" },
            { serialNumber: "04", districtName: "Aurangabad", districtCode: "AUR" },
            { serialNumber: "05", districtName: "Beed", districtCode: "BEE" },
            { serialNumber: "06", districtName: "Bhandara", districtCode: "BHA" },
            { serialNumber: "07", districtName: "Buldhana", districtCode: "BUL" },
            { serialNumber: "08", districtName: "Chandrapur", districtCode: "CHA" },
            { serialNumber: "09", districtName: "Dhule", districtCode: "DHU" },
            { serialNumber: "10", districtName: "Gadchiroli", districtCode: "GAD" },
            { serialNumber: "11", districtName: "Gondia", districtCode: "GON" },
            { serialNumber: "12", districtName: "Hingoli", districtCode: "HIN" },
            { serialNumber: "13", districtName: "Jalgaon", districtCode: "JAL" },
            { serialNumber: "14", districtName: "Jalna", districtCode: "JAL" },
            { serialNumber: "15", districtName: "Kolhapur", districtCode: "KOL" },
            { serialNumber: "16", districtName: "Latur", districtCode: "LAT" },
            { serialNumber: "17", districtName: "Mumbai City", districtCode: "MUM" },
            { serialNumber: "18", districtName: "Mumbai Suburban", districtCode: "SUB" },
            { serialNumber: "19", districtName: "Nagpur", districtCode: "NAG" },
            { serialNumber: "20", districtName: "Nanded", districtCode: "NAN" },
            { serialNumber: "21", districtName: "Nashik", districtCode: "NAS" },
            { serialNumber: "22", districtName: "Osmanabad", districtCode: "OSM" },
            { serialNumber: "23", districtName: "Palghar", districtCode: "PAL" },
            { serialNumber: "24", districtName: "Parbhani", districtCode: "PAR" },
            { serialNumber: "25", districtName: "Pune", districtCode: "PUN" },
            { serialNumber: "26", districtName: "Raigad", districtCode: "RAI" },
            { serialNumber: "27", districtName: "Ratnagiri", districtCode: "RAT" },
            { serialNumber: "28", districtName: "Sangli", districtCode: "SAN" },
            { serialNumber: "29", districtName: "Satara", districtCode: "SAT" },
            { serialNumber: "30", districtName: "Sindhudurg", districtCode: "SIN" },
            { serialNumber: "31", districtName: "Solapur", districtCode: "SOL" },
            { serialNumber: "32", districtName: "Thane", districtCode: "THA" },
            { serialNumber: "33", districtName: "Wardha", districtCode: "WAR" },
            { serialNumber: "34", districtName: "Washim", districtCode: "WAS" },
            { serialNumber: "35", districtName: "Yavatmal", districtCode: "YAV" },
            { serialNumber: "36", districtName: "Gondia", districtCode: "GON" }
        ],
        totalDistrictCount: 36
    },
    {
        state: "Manipur",
        stateCode: "MN",
        districts: [
            { serialNumber: "01", districtName: "Bishnupur", districtCode: "BIS" },
            { serialNumber: "02", districtName: "Churachandpur", districtCode: "CHU" },
            { serialNumber: "03", districtName: "Chandel", districtCode: "CHA" },
            { serialNumber: "04", districtName: "Imphal East", districtCode: "IME" },
            { serialNumber: "05", districtName: "Imphal West", districtCode: "IMW" },
            { serialNumber: "06", districtName: "Jiribam", districtCode: "JIR" },
            { serialNumber: "07", districtName: "Kakching", districtCode: "KAK" },
            { serialNumber: "08", districtName: "Kamjong", districtCode: "KAM" },
            { serialNumber: "09", districtName: "Kangpokpi", districtCode: "KAN" },
            { serialNumber: "10", districtName: "Noney", districtCode: "NON" },
            { serialNumber: "11", districtName: "Pherzawl", districtCode: "PHE" },
            { serialNumber: "12", districtName: "Senapati", districtCode: "SEN" },
            { serialNumber: "13", districtName: "Tamenglong", districtCode: "TAM" },
            { serialNumber: "14", districtName: "Tengnoupal", districtCode: "TEN" },
            { serialNumber: "15", districtName: "Ukhrul", districtCode: "UKH" },
            { serialNumber: "16", districtName: "Bishnupur", districtCode: "BIS" }
        ],
        totalDistrictCount: 16
    },
    {
        state: "Meghalaya",
        stateCode: "ML",
        districts: [
            { serialNumber: "01", districtName: "East Garo Hills", districtCode: "EGR" },
            { serialNumber: "02", districtName: "East Jaintia Hills", districtCode: "EJI" },
            { serialNumber: "03", districtName: "East Khasi Hills", districtCode: "EKH" },
            { serialNumber: "04", districtName: "North Garo Hills", districtCode: "NGR" },
            { serialNumber: "05", districtName: "Ri-Bhoi", districtCode: "RIB" },
            { serialNumber: "06", districtName: "South Garo Hills", districtCode: "SGR" },
            { serialNumber: "07", districtName: "South West Garo Hills", districtCode: "SWG" },
            { serialNumber: "08", districtName: "South West Khasi Hills", districtCode: "SWK" },
            { serialNumber: "09", districtName: "West Garo Hills", districtCode: "WGR" },
            { serialNumber: "10", districtName: "West Jaintia Hills", districtCode: "WJI" },
            { serialNumber: "11", districtName: "West Khasi Hills", districtCode: "WKH" },
            { serialNumber: "12", districtName: "South West Khasi Hills", districtCode: "SWK" }
        ],
        totalDistrictCount: 12
    },
    {
        state: "Mizoram",
        stateCode: "MZ",
        districts: [
            { serialNumber: "01", districtName: "Aizawl", districtCode: "AIZ" },
            { serialNumber: "02", districtName: "Champhai", districtCode: "CHA" },
            { serialNumber: "03", districtName: "Kolasib", districtCode: "KOL" },
            { serialNumber: "04", districtName: "Lawngtlai", districtCode: "LAw" },
            { serialNumber: "05", districtName: "Lunglei", districtCode: "LUN" },
            { serialNumber: "06", districtName: "Mamit", districtCode: "MAM" },
            { serialNumber: "07", districtName: "Saitual", districtCode: "SAI" },
            { serialNumber: "08", districtName: "Serchhip", districtCode: "SER" },
            { serialNumber: "09", districtName: "Hnahthial", districtCode: "HNA" },
            { serialNumber: "10", districtName: "Khawzawl", districtCode: "KHA" },
            { serialNumber: "11", districtName: "Khawzawl", districtCode: "KHA" }
        ],
        totalDistrictCount: 11
    },
    {
        state: "Nagaland",
        stateCode: "NL",
        districts: [
            { serialNumber: "01", districtName: "Dimapur", districtCode: "DIM" },
            { serialNumber: "02", districtName: "Kiphire", districtCode: "KIP" },
            { serialNumber: "03", districtName: "Kohima", districtCode: "KOH" },
            { serialNumber: "04", districtName: "Longleng", districtCode: "LON" },
            { serialNumber: "05", districtName: "Mokokchung", districtCode: "MOK" },
            { serialNumber: "06", districtName: "Mon", districtCode: "MON" },
            { serialNumber: "07", districtName: "Peren", districtCode: "PER" },
            { serialNumber: "08", districtName: "Phek", districtCode: "PHE" },
            { serialNumber: "09", districtName: "Tuensang", districtCode: "TUE" },
            { serialNumber: "10", districtName: "Wokha", districtCode: "WOK" },
            { serialNumber: "11", districtName: "Zunheboto", districtCode: "ZUN" },
            { serialNumber: "12", districtName: "Kohima", districtCode: "KOH" },
            { serialNumber: "13", districtName: "Zunheboto", districtCode: "ZUN" },
            { serialNumber: "14", districtName: "Mokokchung", districtCode: "MOK" },
            { serialNumber: "15", districtName: "Mon", districtCode: "MON" },
            { serialNumber: "16", districtName: "Dimapur", districtCode: "DIM" }
        ],
        totalDistrictCount: 16
    },
    {
        state: "Odisha",
        stateCode: "OD",
        districts: [
            { serialNumber: "01", districtName: "Angul", districtCode: "ANG" },
            { serialNumber: "02", districtName: "Bargarh", districtCode: "BAR" },
            { serialNumber: "03", districtName: "Boudh", districtCode: "BOU" },
            { serialNumber: "04", districtName: "Cuttack", districtCode: "CUT" },
            { serialNumber: "05", districtName: "Deogarh", districtCode: "DEO" },
            { serialNumber: "06", districtName: "Dhenkanal", districtCode: "DHE" },
            { serialNumber: "07", districtName: "Gajapati", districtCode: "GAJ" },
            { serialNumber: "08", districtName: "Ganjam", districtCode: "GAN" },
            { serialNumber: "09", districtName: "Jagatsinghpur", districtCode: "JAG" },
            { serialNumber: "10", districtName: "Jajpur", districtCode: "JAJ" },
            { serialNumber: "11", districtName: "Jhargram", districtCode: "JHA" },
            { serialNumber: "12", districtName: "Kalahandi", districtCode: "KAL" },
            { serialNumber: "13", districtName: "Kandhamal", districtCode: "KAN" },
            { serialNumber: "14", districtName: "Kendrapara", districtCode: "KEN" },
            { serialNumber: "15", districtName: "Kendujhar", districtCode: "KEN" },
            { serialNumber: "16", districtName: "Khurda", districtCode: "KHU" },
            { serialNumber: "17", districtName: "Koraput", districtCode: "KOR" },
            { serialNumber: "18", districtName: "Malkangiri", districtCode: "MAL" },
            { serialNumber: "19", districtName: "Nabarangpur", districtCode: "NAB" },
            { serialNumber: "20", districtName: "Nayagarh", districtCode: "NAY" },
            { serialNumber: "21", districtName: "Nuapada", districtCode: "NUA" },
            { serialNumber: "22", districtName: "Puri", districtCode: "PUR" },
            { serialNumber: "23", districtName: "Rayagada", districtCode: "RAY" },
            { serialNumber: "24", districtName: "Sambalpur", districtCode: "SAM" },
            { serialNumber: "25", districtName: "Subarnapur", districtCode: "SUB" },
            { serialNumber: "26", districtName: "Sundargarh", districtCode: "SUN" },
            { serialNumber: "27", districtName: "Boudh", districtCode: "BOU" },
            { serialNumber: "28", districtName: "Jajpur", districtCode: "JAJ" },
            { serialNumber: "29", districtName: "Ganjam", districtCode: "GAN" },
            { serialNumber: "30", districtName: "Khurdha", districtCode: "KHU" }
        ],
        totalDistrictCount: 30
    },
    {
        state: "Punjab",
        stateCode: "PB",
        districts: [
            { serialNumber: "01", districtName: "Amritsar", districtCode: "AMR" },
            { serialNumber: "02", districtName: "Barnala", districtCode: "BAR" },
            { serialNumber: "03", districtName: "Bathinda", districtCode: "BAT" },
            { serialNumber: "04", districtName: "Fatehgarh Sahib", districtCode: "FAT" },
            { serialNumber: "05", districtName: "Firozpur", districtCode: "FIR" },
            { serialNumber: "06", districtName: "Gurdaspur", districtCode: "GUR" },
            { serialNumber: "07", districtName: "Hoshiarpur", districtCode: "HOS" },
            { serialNumber: "08", districtName: "Jalandhar", districtCode: "JAL" },
            { serialNumber: "09", districtName: "Kapurthala", districtCode: "KAP" },
            { serialNumber: "10", districtName: "Ludhiana", districtCode: "LUD" },
            { serialNumber: "11", districtName: "Mansa", districtCode: "MAN" },
            { serialNumber: "12", districtName: "Moga", districtCode: "MOG" },
            { serialNumber: "13", districtName: "Muktsar", districtCode: "MUK" },
            { serialNumber: "14", districtName: "Nawanshahr", districtCode: "NAW" },
            { serialNumber: "15", districtName: "Pathankot", districtCode: "PAT" },
            { serialNumber: "16", districtName: "Patiala", districtCode: "PAT" },
            { serialNumber: "17", districtName: "Rupnagar", districtCode: "RUP" },
            { serialNumber: "18", districtName: "SAS Nagar", districtCode: "SAS" },
            { serialNumber: "19", districtName: "Sangrur", districtCode: "SAN" },
            { serialNumber: "20", districtName: "Sri Muktsar Sahib", districtCode: "SMU" },
            { serialNumber: "21", districtName: "Tarn Taran", districtCode: "TAR" },
            { serialNumber: "22", districtName: "Amritsar", districtCode: "AMR" },
            { serialNumber: "23", districtName: "Fatehgarh Sahib", districtCode: "FAT" }
        ],
        totalDistrictCount: 23
    },
    {
        state: "Rajasthan",
        stateCode: "RJ",
        districts: [
            { serialNumber: "01", districtName: "Ajmer", districtCode: "AJM" },
            { serialNumber: "02", districtName: "Alwar", districtCode: "ALW" },
            { serialNumber: "03", districtName: "Banswara", districtCode: "BAN" },
            { serialNumber: "04", districtName: "Baran", districtCode: "BAR" },
            { serialNumber: "05", districtName: "Barmer", districtCode: "BAR" },
            { serialNumber: "06", districtName: "Bharatpur", districtCode: "BHA" },
            { serialNumber: "07", districtName: "Bhilwara", districtCode: "BHI" },
            { serialNumber: "08", districtName: "Bikaner", districtCode: "BIK" },
            { serialNumber: "09", districtName: "Bundi", districtCode: "BUN" },
            { serialNumber: "10", districtName: "Chittorgarh", districtCode: "CHI" },
            { serialNumber: "11", districtName: "Churu", districtCode: "CHU" },
            { serialNumber: "12", districtName: "Dausa", districtCode: "DAU" },
            { serialNumber: "13", districtName: "Dholpur", districtCode: "DHO" },
            { serialNumber: "14", districtName: "Dungarpur", districtCode: "DUN" },
            { serialNumber: "15", districtName: "Hanumangarh", districtCode: "HAN" },
            { serialNumber: "16", districtName: "Jaipur", districtCode: "JAI" },
            { serialNumber: "17", districtName: "Jaisalmer", districtCode: "JAI" },
            { serialNumber: "18", districtName: "Jalore", districtCode: "JAL" },
            { serialNumber: "19", districtName: "Jhalawar", districtCode: "JHA" },
            { serialNumber: "20", districtName: "Jhunjhunu", districtCode: "JHU" },
            { serialNumber: "21", districtName: "Jodhpur", districtCode: "JOD" },
            { serialNumber: "22", districtName: "Karauli", districtCode: "KAR" },
            { serialNumber: "23", districtName: "Nagaur", districtCode: "NAG" },
            { serialNumber: "24", districtName: "Pali", districtCode: "PAL" },
            { serialNumber: "25", districtName: "Pratapgarh", districtCode: "PRA" },
            { serialNumber: "26", districtName: "Rajsamand", districtCode: "RAJ" },
            { serialNumber: "27", districtName: "Sawai Madhopur", districtCode: "SAW" },
            { serialNumber: "28", districtName: "Sikar", districtCode: "SIK" },
            { serialNumber: "29", districtName: "Sirohi", districtCode: "SIR" },
            { serialNumber: "30", districtName: "Tonk", districtCode: "TON" },
            { serialNumber: "31", districtName: "Udaipur", districtCode: "UDA" },
            { serialNumber: "32", districtName: "Rajasthan", districtCode: "RAJ" },
            { serialNumber: "33", districtName: "Bhilwara", districtCode: "BHI" },
            { serialNumber: "34", districtName: "Banswara", districtCode: "BAN" },
            { serialNumber: "35", districtName: "Barmer", districtCode: "BAR" },
            { serialNumber: "36", districtName: "Jaisalmer", districtCode: "JAI" },
            { serialNumber: "37", districtName: "Churu", districtCode: "CHU" },
            { serialNumber: "38", districtName: "Dausa", districtCode: "DAU" },
            { serialNumber: "39", districtName: "Dungarpur", districtCode: "DUN" },
            { serialNumber: "40", districtName: "Hanumangarh", districtCode: "HAN" },
            { serialNumber: "41", districtName: "Jaipur", districtCode: "JAI" },
            { serialNumber: "42", districtName: "Jalore", districtCode: "JAL" },
            { serialNumber: "43", districtName: "Jhalawar", districtCode: "JHA" },
            { serialNumber: "44", districtName: "Jhunjhunu", districtCode: "JHU" },
            { serialNumber: "45", districtName: "Karauli", districtCode: "KAR" },
            { serialNumber: "46", districtName: "Nagaur", districtCode: "NAG" },
            { serialNumber: "47", districtName: "Pali", districtCode: "PAL" },
            { serialNumber: "48", districtName: "Rajsamand", districtCode: "RAJ" },
            { serialNumber: "49", districtName: "Sawai Madhopur", districtCode: "SAW" },
            { serialNumber: "50", districtName: "Sikar", districtCode: "SIK" }
        ],
        totalDistrictCount: 50
    },
    {
        state: "Sikkim",
        stateCode: "SK",
        districts: [
            { serialNumber: "01", districtName: "Gangtok", districtCode: "GAN" },
            { serialNumber: "02", districtName: "Mangan", districtCode: "MAN" },
            { serialNumber: "03", districtName: "Namchi", districtCode: "NAM" },
            { serialNumber: "04", districtName: "Gyalshing", districtCode: "GYL" },
            { serialNumber: "05", districtName: "Pakyong", districtCode: "PAK" },
            { serialNumber: "06", districtName: "Soreng", districtCode: "SOR" }
        ],
        totalDistrictCount: 6
    },
    {
        state: "Tamil Nadu",
        stateCode: "TN",
        districts: [
            { serialNumber: "01", districtName: "Chennai", districtCode: "CHE" },
            { serialNumber: "02", districtName: "Coimbatore", districtCode: "COI" },
            { serialNumber: "03", districtName: "Cuddalore", districtCode: "CUD" },
            { serialNumber: "04", districtName: "Dharmapuri", districtCode: "DHA" },
            { serialNumber: "05", districtName: "Dindigul", districtCode: "DIN" },
            { serialNumber: "06", districtName: "Erode", districtCode: "ERO" },
            { serialNumber: "07", districtName: "Kallakurichi", districtCode: "KAL" },
            { serialNumber: "08", districtName: "Kancheepuram", districtCode: "KAN" },
            { serialNumber: "09", districtName: "Kanyakumari", districtCode: "KAY" },
            { serialNumber: "10", districtName: "Karur", districtCode: "KAR" },
            { serialNumber: "11", districtName: "Krishnagiri", districtCode: "KRI" },
            { serialNumber: "12", districtName: "Madurai", districtCode: "MAD" },
            { serialNumber: "13", districtName: "Nagapattinam", districtCode: "NAG" },
            { serialNumber: "14", districtName: "Namakkal", districtCode: "NAM" },
            { serialNumber: "15", districtName: "Nilgiris", districtCode: "NIL" },
            { serialNumber: "16", districtName: "Perambalur", districtCode: "PER" },
            { serialNumber: "17", districtName: "Pudukkottai", districtCode: "PUD" },
            { serialNumber: "18", districtName: "Ramanathapuram", districtCode: "RAM" },
            { serialNumber: "19", districtName: "Ranipet", districtCode: "RAN" },
            { serialNumber: "20", districtName: "Salem", districtCode: "SAL" },
            { serialNumber: "21", districtName: "Sivaganga", districtCode: "SIV" },
            { serialNumber: "22", districtName: "Tenkasi", districtCode: "TEN" },
            { serialNumber: "23", districtName: "Thanjavur", districtCode: "THA" },
            { serialNumber: "24", districtName: "Theni", districtCode: "THE" },
            { serialNumber: "25", districtName: "Thiruvallur", districtCode: "THI" },
            { serialNumber: "26", districtName: "Thiruvannamalai", districtCode: "THU" },
            { serialNumber: "27", districtName: "Tirunelveli", districtCode: "TIR" },
            { serialNumber: "28", districtName: "Tirupathur", districtCode: "TIR" },
            { serialNumber: "29", districtName: "Tiruppur", districtCode: "TIR" },
            { serialNumber: "30", districtName: "Tiruchirappalli", districtCode: "TIR" },
            { serialNumber: "31", districtName: "Vellore", districtCode: "VEL" },
            { serialNumber: "32", districtName: "Viluppuram", districtCode: "VIL" },
            { serialNumber: "33", districtName: "Virudhunagar", districtCode: "VIR" },
            { serialNumber: "34", districtName: "Tiruppur", districtCode: "TIR" },
            { serialNumber: "35", districtName: "Ariyalur", districtCode: "ARI" },
            { serialNumber: "36", districtName: "Chengalpattu", districtCode: "CHE" },
            { serialNumber: "37", districtName: "Cuddalore", districtCode: "CUD" },
            { serialNumber: "38", districtName: "Kallakurichi", districtCode: "KAL" }
        ],
        totalDistrictCount: 38
    },
    {
        state: "Telangana",
        stateCode: "TS",
        districts: [
            { serialNumber: "01", districtName: "Adilabad", districtCode: "ADI" },
            { serialNumber: "02", districtName: "Bhadradri Kothagudem", districtCode: "BHA" },
            { serialNumber: "03", districtName: "Bengaluru", districtCode: "BEN" },
            { serialNumber: "04", districtName: "Hyderabad", districtCode: "HYD" },
            { serialNumber: "05", districtName: "Jagtial", districtCode: "JAG" },
            { serialNumber: "06", districtName: "Jammikunta", districtCode: "JAM" },
            { serialNumber: "07", districtName: "Jangaon", districtCode: "JAN" },
            { serialNumber: "08", districtName: "Jio", districtCode: "JIO" },
            { serialNumber: "09", districtName: "Karimnagar", districtCode: "KAR" },
            { serialNumber: "10", districtName: "Khammam", districtCode: "KHA" },
            { serialNumber: "11", districtName: "Komaram Bheem", districtCode: "KOM" },
            { serialNumber: "12", districtName: "Mahabubabad", districtCode: "MAH" },
            { serialNumber: "13", districtName: "Mahabubnagar", districtCode: "MAH" },
            { serialNumber: "14", districtName: "Mancherial", districtCode: "MAN" },
            { serialNumber: "15", districtName: "Medak", districtCode: "MED" },
            { serialNumber: "16", districtName: "Medchal", districtCode: "MED" },
            { serialNumber: "17", districtName: "Nalgonda", districtCode: "NAL" },
            { serialNumber: "18", districtName: "Nagarkurnool", districtCode: "NAG" },
            { serialNumber: "19", districtName: "Nirmal", districtCode: "NIR" },
            { serialNumber: "20", districtName: "Nizamabad", districtCode: "NIZ" },
            { serialNumber: "21", districtName: "Peddapalli", districtCode: "PED" },
            { serialNumber: "22", districtName: "Rajanna Sircilla", districtCode: "RAJ" },
            { serialNumber: "23", districtName: "Rangareddy", districtCode: "RAN" },
            { serialNumber: "24", districtName: "Sangareddy", districtCode: "SAN" },
            { serialNumber: "25", districtName: "Warangal (Rural)", districtCode: "WAR" },
            { serialNumber: "26", districtName: "Warangal (Urban)", districtCode: "WAR" },
            { serialNumber: "27", districtName: "Jagtial", districtCode: "JAG" },
            { serialNumber: "28", districtName: "Jangaon", districtCode: "JAN" },
            { serialNumber: "29", districtName: "Kamareddy", districtCode: "KAM" },
            { serialNumber: "30", districtName: "Karimnagar", districtCode: "KAR" },
            { serialNumber: "31", districtName: "Khammam", districtCode: "KHA" },
            { serialNumber: "32", districtName: "Komaram Bheem", districtCode: "KOM" },
            { serialNumber: "33", districtName: "Medak", districtCode: "MED" }
        ],
        totalDistrictCount: 33
    },
    {
        state: "Tripura",
        stateCode: "TR",
        districts: [
            { serialNumber: "01", districtName: "Agartala", districtCode: "AGA" },
            { serialNumber: "02", districtName: "Dhalai", districtCode: "DHA" },
            { serialNumber: "03", districtName: "Khowai", districtCode: "KHO" },
            { serialNumber: "04", districtName: "North Tripura", districtCode: "NTR" },
            { serialNumber: "05", districtName: "Sepahijala", districtCode: "SEP" },
            { serialNumber: "06", districtName: "South Tripura", districtCode: "STR" },
            { serialNumber: "07", districtName: "Unakoti", districtCode: "UNA" },
            { serialNumber: "08", districtName: "West Tripura", districtCode: "WTR" }
        ],
        totalDistrictCount: 8
    },
    {
        state: "Uttar Pradesh",
        stateCode: "UP",
        districts: [
            { serialNumber: "01", districtName: "Agra", districtCode: "AGR" },
            { serialNumber: "02", districtName: "Aligarh", districtCode: "ALI" },
            { serialNumber: "03", districtName: "Allahabad", districtCode: "ALL" },
            { serialNumber: "04", districtName: "Ambedkar Nagar", districtCode: "AMB" },
            { serialNumber: "05", districtName: "Amethi", districtCode: "AME" },
            { serialNumber: "06", districtName: "Amroha", districtCode: "AMR" },
            { serialNumber: "07", districtName: "Auraiya", districtCode: "AUR" },
            { serialNumber: "08", districtName: "Azamgarh", districtCode: "AZA" },
            { serialNumber: "09", districtName: "Baghpat", districtCode: "BAG" },
            { serialNumber: "10", districtName: "Bahraich", districtCode: "BAH" },
            { serialNumber: "11", districtName: "Ballia", districtCode: "BAL" },
            { serialNumber: "12", districtName: "Banda", districtCode: "BAN" },
            { serialNumber: "13", districtName: "Bara Banki", districtCode: "BAR" },
            { serialNumber: "14", districtName: "Bareilly", districtCode: "BAR" },
            { serialNumber: "15", districtName: "Basti", districtCode: "BAS" },
            { serialNumber: "16", districtName: "Bhadohi", districtCode: "BHA" },
            { serialNumber: "17", districtName: "Bijnor", districtCode: "BIJ" },
            { serialNumber: "18", districtName: "Budaun", districtCode: "BUA" },
            { serialNumber: "19", districtName: "Bulandshahr", districtCode: "BUL" },
            { serialNumber: "20", districtName: "Chandauli", districtCode: "CHA" },
            { serialNumber: "21", districtName: "Chitrakoot", districtCode: "CHI" },
            { serialNumber: "22", districtName: "Deoria", districtCode: "DEO" },
            { serialNumber: "23", districtName: "Etah", districtCode: "ETA" },
            { serialNumber: "24", districtName: "Etawah", districtCode: "ETA" },
            { serialNumber: "25", districtName: "Faizabad", districtCode: "FAI" },
            { serialNumber: "26", districtName: "Farrukhabad", districtCode: "FAR" },
            { serialNumber: "27", districtName: "Fatehpur", districtCode: "FAT" },
            { serialNumber: "28", districtName: "Fatehgarh", districtCode: "FAT" },
            { serialNumber: "29", districtName: "Gautam Buddha Nagar", districtCode: "GAU" },
            { serialNumber: "30", districtName: "Ghaziabad", districtCode: "GHA" },
            { serialNumber: "31", districtName: "Ghazipur", districtCode: "GHA" },
            { serialNumber: "32", districtName: "Gonda", districtCode: "GON" },
            { serialNumber: "33", districtName: "Gorakhpur", districtCode: "GOR" },
            { serialNumber: "34", districtName: "Hamirpur", districtCode: "HAM" },
            { serialNumber: "35", districtName: "Hapur", districtCode: "HAP" },
            { serialNumber: "36", districtName: "Hardoi", districtCode: "HAR" },
            { serialNumber: "37", districtName: "Hathras", districtCode: "HAT" },
            { serialNumber: "38", districtName: "Jalaun", districtCode: "JAL" },
            { serialNumber: "39", districtName: "Jaunpur", districtCode: "JAU" },
            { serialNumber: "40", districtName: "Jhansi", districtCode: "JHA" },
            { serialNumber: "41", districtName: "Jyotiba Phule Nagar", districtCode: "JYO" },
            { serialNumber: "42", districtName: "Kanpur Dehat", districtCode: "KAN" },
            { serialNumber: "43", districtName: "Kanpur", districtCode: "KAN" },
            { serialNumber: "44", districtName: "Kanshiram Nagar", districtCode: "KAN" },
            { serialNumber: "45", districtName: "Kheri", districtCode: "KHE" },
            { serialNumber: "46", districtName: "Kushinagar", districtCode: "KUS" },
            { serialNumber: "47", districtName: "Lakhimpur Kheri", districtCode: "LAK" },
            { serialNumber: "48", districtName: "Lalitpur", districtCode: "LAL" },
            { serialNumber: "49", districtName: "Lucknow", districtCode: "LUC" },
            { serialNumber: "50", districtName: "Maharajganj", districtCode: "MAH" },
            { serialNumber: "51", districtName: "Mahoba", districtCode: "MAH" },
            { serialNumber: "52", districtName: "Mainpuri", districtCode: "MAI" },
            { serialNumber: "53", districtName: "Mathura", districtCode: "MAT" },
            { serialNumber: "54", districtName: "Meerut", districtCode: "MEE" },
            { serialNumber: "55", districtName: "Mirzapur", districtCode: "MIR" },
            { serialNumber: "56", districtName: "Moradabad", districtCode: "MOR" },
            { serialNumber: "57", districtName: "Muzaffarnagar", districtCode: "MUZ" },
            { serialNumber: "58", districtName: "Pilibhit", districtCode: "PIL" },
            { serialNumber: "59", districtName: "Pratapgarh", districtCode: "PRA" },
            { serialNumber: "60", districtName: "Raebareli", districtCode: "RAE" },
            { serialNumber: "61", districtName: "Rae Bareli", districtCode: "RAE" },
            { serialNumber: "62", districtName: "Rampur", districtCode: "RAM" },
            { serialNumber: "63", districtName: "Saharanpur", districtCode: "SAH" },
            { serialNumber: "64", districtName: "Sant Kabir Nagar", districtCode: "SAN" },
            { serialNumber: "65", districtName: "Shahjahanpur", districtCode: "SHA" },
            { serialNumber: "66", districtName: "Shamli", districtCode: "SHA" },
            { serialNumber: "67", districtName: "Shravasti", districtCode: "SHR" },
            { serialNumber: "68", districtName: "Siddharthnagar", districtCode: "SID" },
            { serialNumber: "69", districtName: "Sitapur", districtCode: "SIT" },
            { serialNumber: "70", districtName: "Sonbhadra", districtCode: "SON" },
            { serialNumber: "71", districtName: "Sultanpur", districtCode: "SUL" },
            { serialNumber: "72", districtName: "Unnao", districtCode: "UNN" },
            { serialNumber: "73", districtName: "Varanasi", districtCode: "VAR" },
            { serialNumber: "74", districtName: "Amroha", districtCode: "AMR" },
            { serialNumber: "75", districtName: "Hapur", districtCode: "HAP" }
        ],
        totalDistrictCount: 75
    },
    {
        state: "Uttarakhand",
        stateCode: "UK",
        districts: [
            { serialNumber: "01", districtName: "Almora", districtCode: "ALM" },
            { serialNumber: "02", districtName: "Bageshwar", districtCode: "BAG" },
            { serialNumber: "03", districtName: "Bharatpur", districtCode: "BHA" },
            { serialNumber: "04", districtName: "Chamoli", districtCode: "CHA" },
            { serialNumber: "05", districtName: "Champawat", districtCode: "CHA" },
            { serialNumber: "06", districtName: "Dehradun", districtCode: "DEA" },
            { serialNumber: "07", districtName: "Haridwar", districtCode: "HAR" },
            { serialNumber: "08", districtName: "Nainital", districtCode: "NAI" },
            { serialNumber: "09", districtName: "Pauri Garhwal", districtCode: "PAU" },
            { serialNumber: "10", districtName: "Pithoragarh", districtCode: "PIT" },
            { serialNumber: "11", districtName: "Rudraprayag", districtCode: "RUD" },
            { serialNumber: "12", districtName: "Tehri Garhwal", districtCode: "TEH" },
            { serialNumber: "13", districtName: "Udham Singh Nagar", districtCode: "UDH" }
        ],
        totalDistrictCount: 13
    },
    {
        state: "West Bengal",
        stateCode: "WB",
        districts: [
            { serialNumber: "01", districtName: "Alipurduar", districtCode: "ALI" },
            { serialNumber: "02", districtName: "Bankura", districtCode: "BAN" },
            { serialNumber: "03", districtName: "Bardhaman", districtCode: "BAR" },
            { serialNumber: "04", districtName: "Birbhum", districtCode: "BIR" },
            { serialNumber: "05", districtName: "Bhowmick", districtCode: "BHO" },
            { serialNumber: "06", districtName: "Cooch Behar", districtCode: "COO" },
            { serialNumber: "07", districtName: "Dakshin Dinajpur", districtCode: "DAK" },
            { serialNumber: "08", districtName: "Darjeeling", districtCode: "DAR" },
            { serialNumber: "09", districtName: "Hooghly", districtCode: "HOO" },
            { serialNumber: "10", districtName: "Howrah", districtCode: "HOW" },
            { serialNumber: "11", districtName: "Jalpaiguri", districtCode: "JAL" },
            { serialNumber: "12", districtName: "Jhargram", districtCode: "JHA" },
            { serialNumber: "13", districtName: "Kolkata", districtCode: "KOL" },
            { serialNumber: "14", districtName: "Malda", districtCode: "MAL" },
            { serialNumber: "15", districtName: "Murarai", districtCode: "MUR" },
            { serialNumber: "16", districtName: "Nadia", districtCode: "NAD" },
            { serialNumber: "17", districtName: "North 24 Parganas", districtCode: "N24" },
            { serialNumber: "18", districtName: "Paschim Bardhaman", districtCode: "PAS" },
            { serialNumber: "19", districtName: "Purba Bardhaman", districtCode: "PUR" },
            { serialNumber: "20", districtName: "Purulia", districtCode: "PUR" },
            { serialNumber: "21", districtName: "South 24 Parganas", districtCode: "S24" },
            { serialNumber: "22", districtName: "Uttar Dinajpur", districtCode: "UTT" },
            { serialNumber: "23", districtName: "Jalpaiguri", districtCode: "JAL" }
        ],
        totalDistrictCount: 23
    },
    {
        state: "Andaman and Nicobar Islands",
        stateCode: "AN",
        districts: [
            { serialNumber: "01", districtName: "Andaman", districtCode: "AND" },
            { serialNumber: "02", districtName: "Nicobar", districtCode: "NIC" },
            { serialNumber: "03", districtName: "North and Middle Andaman", districtCode: "NMA" }
        ],
        totalDistrictCount: 3
    },
    {
        state: "Chandigarh",
        stateCode: "CH",
        districts: [
            { serialNumber: "01", districtName: "Chandigarh", districtCode: "CHA" }
        ],
        totalDistrictCount: 1
    },
    {
        state: "Dadra and Nagar Haveli and Daman and Diu",
        stateCode: "DN",
        districts: [
            { serialNumber: "01", districtName: "Dadra and Nagar Haveli", districtCode: "DNH" },
            { serialNumber: "02", districtName: "Daman", districtCode: "DAM" },
            { serialNumber: "03", districtName: "Diu", districtCode: "DIU" }
        ],
        totalDistrictCount: 3
    },
    {
        state: "Delhi",
        stateCode: "DL",
        districts: [
            { serialNumber: "01", districtName: "Central Delhi", districtCode: "CED" },
            { serialNumber: "02", districtName: "East Delhi", districtCode: "EED" },
            { serialNumber: "03", districtName: "New Delhi", districtCode: "NED" },
            { serialNumber: "04", districtName: "North Delhi", districtCode: "NOD" },
            { serialNumber: "05", districtName: "North East Delhi", districtCode: "NED" },
            { serialNumber: "06", districtName: "North West Delhi", districtCode: "NWD" },
            { serialNumber: "07", districtName: "South Delhi", districtCode: "SED" },
            { serialNumber: "08", districtName: "South East Delhi", districtCode: "SED" },
            { serialNumber: "09", districtName: "South West Delhi", districtCode: "SWD" },
            { serialNumber: "10", districtName: "West Delhi", districtCode: "WED" },
            { serialNumber: "11", districtName: "North West Delhi", districtCode: "NWD" }
        ],
        totalDistrictCount: 11
    },
    {
        state: "Lakshadweep",
        stateCode: "LD",
        districts: [
            { serialNumber: "01", districtName: "Lakshadweep", districtCode: "LAK" }
        ],
        totalDistrictCount: 1
    },
    {
        state: "Puducherry",
        stateCode: "PY",
        districts: [
            { serialNumber: "01", districtName: "Karaikal", districtCode: "KAR" },
            { serialNumber: "02", districtName: "Mahe", districtCode: "MAH" },
            { serialNumber: "03", districtName: "Puducherry", districtCode: "PUD" },
            { serialNumber: "04", districtName: "Yanam", districtCode: "YAN" }
        ],
        totalDistrictCount: 4
    },
    {
        state: "Ladakh",
        stateCode: "LA",
        districts: [
            { serialNumber: "01", districtName: "Leh", districtCode: "LEH" },
            { serialNumber: "02", districtName: "Kargil", districtCode: "KAR" }
        ],
        totalDistrictCount: 2
    },
    {
        state: "Jammu and Kashmir",
        stateCode: "JK",
        districts: [
            { serialNumber: "01", districtName: "Jammu", districtCode: "JAM" },
            { serialNumber: "02", districtName: "Kathua", districtCode: "KAT" },
            { serialNumber: "03", districtName: "Samba", districtCode: "SAM" },
            { serialNumber: "04", districtName: "Udhampur", districtCode: "UDH" },
            { serialNumber: "05", districtName: "Ramban", districtCode: "RAM" },
            { serialNumber: "06", districtName: "Doda", districtCode: "DOD" },
            { serialNumber: "07", districtName: "Rajouri", districtCode: "RAJ" },
            { serialNumber: "08", districtName: "Poonch", districtCode: "POO" },
            { serialNumber: "09", districtName: "Anantnag", districtCode: "ANA" },
            { serialNumber: "10", districtName: "Pulwama", districtCode: "PUL" },
            { serialNumber: "11", districtName: "Kulgam", districtCode: "KUL" },
            { serialNumber: "12", districtName: "Shopian", districtCode: "SHO" },
            { serialNumber: "13", districtName: "Srinagar", districtCode: "SRI" },
            { serialNumber: "14", districtName: "Ganderbal", districtCode: "GAN" },
            { serialNumber: "15", districtName: "Budgam", districtCode: "BUD" },
            { serialNumber: "16", districtName: "Kishtwar", districtCode: "KIS" },
            { serialNumber: "17", districtName: "Jammu", districtCode: "JAM" },
            { serialNumber: "18", districtName: "Kathua", districtCode: "KAT" },
            { serialNumber: "19", districtName: "Samba", districtCode: "SAM" },
            { serialNumber: "20", districtName: "Udhampur", districtCode: "UDH" }
        ],
        totalDistrictCount: 20
    }
    
]